### ISSUE TITLE
Portuguese dictionary page wanted

### ISSUE THREAD

**Issue by matthiaswaechter** [haukex/de-en-dict#14] opened 2024-07-25 11:12 UTC
As far as I remember, Beolingus was one of the very few free online Portuguese dictionaries, and I used that quite a bit. So, would it be possible to re-activate the Portuguese dictionary as well?
I do not know about the license details of the Portuguese data base, however.

**Comment by haukex** [comment] 2024-07-25 12:24
Thanks for the feedback - this is a duplicate of #6 (that discussion was in German so far, but it is about both the German-Spanish and German-Portuguese dictionaries)

**Closed as not planned by haukex** 2024-07-25 12:24 UTC
Labels: duplicate, enhancement

**Comment by matthiaswaechter** [comment] 2024-07-25 12:27
Yes true, thanks for the hint. I had read only the title of #6 which is about Spanish ...

**Comment by haukex** [comment] 2024-07-25 12:28
Good point, thanks, I've edited the title of that issue.
