### ISSUE TITLE
What made the old Beolingus stand out

### ISSUE THREAD

**Issue by G3CD** [haukex/de-en-dict#18] opened 2024-08-04 12:11 UTC
Hmm, this might be resolved? I searched for "Gewalt" yesterday and it just gave me a coulle of results, with "Force" being the first without any context or explanation (which was wrong in my context, see below). Today, it gave me the usual context and more options. Which is so very much important!!! Please read on ...

What I liked about the old Beolingus was the amount of options I got with a single search. Like, I was at Christopher Street Day yesterday and wanted to explain someone the origins in English, which was "Polizeigewalt gegen Homosexuelle" (in New York in the late 60's). But when I search for "Gewalt" the new search engine result is "Force". This is just what google does - here's your result, now live with it, love it or leave it!

But what I appreciated about the old search engine, was the context given. "Force" maybe right in a context like "China is a FORCE to deal with" or as the "jurisdiction force" or by "applying force to a piece of metal". But for what I was looking for, it was wrong, "violence" would've been the right word.

If the current search engine just returns "Gewalt = Force", it does not allow that the user to reconsider or understand whether that translation is appropriate. English beginners will in fact just take the "AI's decision" as right and use the wrong word instead. So please DO GIVE EXAMPLES and context. Otherwise, the Beolingus search engine will be just like any other - and obsolete.

Another thing I liked about the old search engine was using it for synonyms - I used to work as a German copywriter and I used Beolingus to come up with more unusual terms (that stick out in an ad). So in the example above, maybe I had a headline with "Gewalt" in my head but I didn't quite like it, I'd then search for "violence" and get a result like "gewaltig" with synonyms like "kolossal" or "überwältigend", which are either old, seldomly used terms or give my thoughts a new direction. 

So, for the love of God, do keep the context, the examples and the insane number of synonyms alive. This is really what distinguishes Beolingus from every other dictionary!

**Comment by haukex** [comment] 2024-08-04 14:14
> I searched for "Gewalt" yesterday and it just gave me a coulle of results, with "Force" being the first without any context or explanation (which was wrong in my context, see below). Today, it gave me the usual context and more options.
> ...
> If the current search engine just returns "Gewalt = Force", it does not allow that the user to reconsider or understand whether that translation is appropriate. English beginners will in fact just take the "AI's decision" as right and use the wrong word instead.

This app always gives *all* the results it can find in the word list, with minor sorting of results (more exact matches first), there is no filtering or AI involved. I just searched for "Gewalt" and got 243 results (over 850 rows including subresults), the first three being "power", "force", and "violence", so unfortunately I can't reproduce what you describe.

The only technical explanation I can think of at the moment is extremely far fetched: If you loaded the app at the exact moment a dictionary update was happening, there is theoretically a tiny chance your browser may only have loaded a partial word list. The last dictionary update seems to have been on Friday, so this is probably not the explanation. If you wanted to be completely sure, you could clear your browser's cache (optionally just for the site zero-g.net) and reload the page. (Also, make sure you're using an up-do-date modern browser such as Firefox, Chrome, or Safari.)

> So, for the love of God, do keep the context, the examples and the insane number of synonyms alive.

Thanks for the feedback - I agree and I have no plans to change the current functionality of the search returning all the results it can. Note that the word list behind the this search is not maintained by me, so perhaps your feedback might be better directed to beolingus@tu-chemnitz.de, though I doubt there are plans to shrink the word list.

If you could provide instructions to reproduce your experience then perhaps there is something to do here, otherwise I am inclined to close this issue.

**Closed as not planned** 2024-08-10 14:54 UTC
Labels: enhancement, invalid
